# Generated by Django 5.0.4 on 2024-04-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_category_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sales',
            field=models.BooleanField(default=False),
        ),
    ]
